/*
 * Copyright 2026 Stéphane Primault <sprimault@users.noreply.github.com>
 * SPDX-License-Identifier: MIT OR Apache-2.0
 */

#ifndef SCREENGINE_H
#define SCREENGINE_H

/* Generated by cbindgen from screengine-ffi. Do not edit by hand: run `make header`. */

#include <stddef.h>
#include <stdint.h>

// ABI version this library implements.
//
// Compare it for equality with the constant from the header you compiled
// against, before any other call, and refuse a library that differs. Adding a
// function or an error code does not change it; everything else does, so a
// different value is a breaking change in either direction.
#define SCG_ABI_VERSION 1

// Alignment, in bytes, guaranteed by `scg_buffer_alloc`.
#define SCG_BUFFER_ALIGNMENT 16

// The only pixel format a texture is loaded from.
//
// One, never zero: a description left zeroed is refused rather than read as a
// valid format. Four bytes per texel, in the memory order of the output
// pixels — a host never has two orders to keep straight.
#define SCG_TEXTURE_FORMAT_RGBA8 1

// Ordered dithering of texture coordinates: the default filter.
//
// Zero, unlike `SCG_TEXTURE_FORMAT_RGBA8`, and for the opposite reason: a
// context that is never configured must render what the engine renders by
// default, so the default has to be the zero value.
#define SCG_FILTER_DITHER 0

// Bilinear blending of the four neighbouring texels, within one mipmap level.
//
// A quality level above the default, at the price of four texel reads per
// pixel instead of one. It replaces dithering rather than adding to it: there
// is no staircase left to hide once coordinates are interpolated.
#define SCG_FILTER_BILINEAR 1

// Success.
#define SCG_OK 0

// A pointer argument was null where the call requires one.
#define SCG_ERR_NULL -1

// An argument is outside what the engine accepts.
#define SCG_ERR_INVALID_ARGUMENT -2

// An allocation failed.
#define SCG_ERR_OUT_OF_MEMORY -3

// The call came out of sequence, such as rendering a tile before the frame began.
#define SCG_ERR_INVALID_STATE -4

// The engine panicked. The object is now faulted; see `SCG_ERR_FAULTED`.
//
// A panic is an engine defect, never a reaction to invalid input. Read the
// message with `scg_last_error` and report it.
#define SCG_ERR_PANIC -5

// A previous call on this object panicked and left it in an unspecified state.
//
// Every call on a faulted object returns this code, except `scg_last_error`
// and the destructor, which stay available so the host can read the cause and
// release the object.
#define SCG_ERR_FAULTED -6

// Deprecated name of `SCG_ERR_FAULTED`, same value. Kept so that hosts written
// against an earlier header still compile; it will not be removed before 1.0.
#define SCG_ERR_POISONED -6

// A lookup by stable identifier found nothing.
//
// No call returns it yet: an identifier missing from a file is caught while
// loading it, and an index beyond its count is a fault in the call. It is
// defined now because a published code never changes meaning.
#define SCG_ERR_UNKNOWN_RESOURCE -100

// The block is not a data file this library can read.
//
// The fault is in the content, not in the call: report it to the user as a bad
// asset, not to the developer as a misuse. Read the message with
// `scg_last_error(NULL)` for what was rejected. Unknown section kinds are
// rejected too, deliberately: silently skipping one would render a different
// image from the same file, without an error.
#define SCG_ERR_INVALID_FORMAT -101

// The signature and kind are right, but this library does not read that format
// version.
//
// The only one of the three data codes that says what to do: take a newer
// library, or export the data again.
#define SCG_ERR_UNSUPPORTED_FORMAT_VERSION -102

// An opaque rendering context.
//
// Created by `scg_create`, released by `scg_destroy`. Use it from one thread
// at a time, with a single exception: between `scg_frame_begin` and
// `scg_frame_end`, distinct tiles may be rendered by `scg_frame_tile` from
// distinct threads. Two contexts are independent and may each serve their own
// thread.
typedef struct ScgContext ScgContext;

// An opaque handle to a loaded mesh.
//
// Created by `scg_mesh_load`, released by `scg_mesh_destroy`. It belongs to no
// context: the same mesh may be submitted to several, from several threads.
typedef struct ScgMesh ScgMesh;

// An opaque handle to a loaded texture.
//
// Created by `scg_texture_load`, released by `scg_texture_destroy`. It belongs
// to no context: the same texture may be submitted to several, from several
// threads, and the engine keeps it alive for as long as a frame references it.
typedef struct ScgTexture ScgTexture;

// Configuration passed to `scg_create`.
//
// Zero the whole structure before filling it in. The reserved fields must be
// zero: that is what lets a later version give one a meaning without breaking
// bindings already written against this header.
//
// Every field is a `uint32_t`, so the offsets are the same on every target —
// including 32-bit ones, where a `size_t` field would not be.
typedef struct ScgContextConfig {
  // Widest internal resolution this context will ever render, in pixels.
  // From 1 to 2048. Every per-frame buffer is sized for it at creation.
  uint32_t max_width;
  // Tallest internal resolution this context will ever render, in pixels.
  // From 1 to 2048.
  uint32_t max_height;
  // Initial internal width in pixels, at most `max_width`.
  uint32_t width;
  // Initial internal height in pixels, at most `max_height`.
  uint32_t height;
  // Tile side in pixels: 32 or 64. Any other value is rejected.
  uint32_t tile_size;
  // Triangles one frame may hold, or 0 for the default of 16384.
  //
  // This counts *prepared* triangles: clipping against the near plane turns
  // one submitted triangle into up to six, and `scg_submit` rejects the
  // batch that would exceed the capacity, never a frame already submitted.
  //
  // This field was reserved in ABI version 1 and reserved fields had to be
  // zero, so a host written against that header keeps the default and needs
  // no change; `SCG_ABI_VERSION` is unchanged.
  uint32_t max_triangles;
  // Reserved. Must be zero.
  uint32_t reserved1;
  // Reserved. Must be zero.
  uint32_t reserved2;
} ScgContextConfig;

// Where the camera is, and how wide it sees.
//
// The world is right-handed with Z up. With the identity orientation
// `{0, 0, 0, 1}`, the camera looks towards world +X, with the zenith towards
// the top of the screen and world −Y towards the right. Naming the third axis
// matters: "looking towards +X" alone leaves the roll undetermined, and roll
// is what a sign mistake flips without changing where the camera points.
//
// The quaternion is stored `x, y, z, w` — the real part last — and is
// normalised by the engine, so it need not be unit.
typedef struct ScgCamera {
  // Position in world space: x, y, z.
  float position[3];
  // Orientation as a quaternion: x, y, z, w.
  float orientation[4];
  // Vertical field of view in radians, within ]0, pi[.
  //
  // Rejected on the radians themselves, before any conversion: three half
  // turns would otherwise fold into one and be accepted silently.
  float fov_y;
  // Near plane distance, positive and finite.
  //
  // Not named `near`: `windows.h` still defines `near` and `far` as empty
  // macros, inherited from 16-bit segmented memory, and a field by that name
  // vanishes in any translation unit that includes it first.
  float near_plane;
} ScgCamera;

// The output curve applied while each tile is copied out: an affine per
// channel, then gamma.
//
// Each channel goes through `x·gain + offset`, clamped to [0, 1], then
// `^(1/gamma)`. The affine is the most general transform that stays local to
// one pixel and one channel: it holds contrast, black level and tint at once.
// A gain alone can lift neither a black nor lower a white, and gamma fixes
// both ends — that family of images is reachable only this way.
//
// `gamma` is the display gamma, in the sense where **2.2 brightens**, within
// ]0, 8]. Gains are within [0, 4], offsets within [-1, 1], and the affine
// applies **before** gamma: it corrects the source, gamma encodes for the
// display, and that is the order in which they read. Gain and gamma commute up
// to reparametrisation — `(a·x)^γ = a^γ·x^γ` — so no image is out of reach
// either way; what the order fixes is what the number means. **It will never
// change**: a host that had set its parameters would otherwise get a different
// image with no version to warn it.
//
// The curve never writes alpha, which the engine forces opaque as the contract
// promises.
//
// **What the reserved fields can ever hold.** They must be zero, and the
// extension rule promises that a host written before one of them means
// anything gets the default behaviour by passing zeros. A setting whose
// neutral value is one — a further gain, a saturation — therefore **cannot**
// go there as such: only additive settings can, whose neutral is zero. Should
// a multiplicative one be wanted later, it has to be expressed as a departure
// from neutral to fit. Written here so that the constraint steers the design
// instead of being discovered against it — which is why the offsets are in
// this struct from the start rather than left for later, where three fields
// would no longer have fitted in two reserved ones.
typedef struct ScgGrade {
  // Display gamma, within ]0, 8].
  float gamma;
  // Red gain, within [0, 4], applied before gamma.
  float gain_r;
  // Green gain.
  float gain_g;
  // Blue gain.
  float gain_b;
  // Red offset, within [-1, 1], added after the gain.
  float offset_r;
  // Green offset.
  float offset_g;
  // Blue offset.
  float offset_b;
  // Reserved, must be zero.
  uint32_t reserved0;
  // Reserved, must be zero.
  uint32_t reserved1;
} ScgGrade;

// A point light that adds to the lighting of a surface.
//
// Twenty bytes, offsets 0 to 19 on every target, with no padding.
//
// **Its falloff is computed per vertex, not per pixel.** There is no distance
// on the integer side of the pipeline, which begins at projection. A wall of
// two triangles therefore renders a gradient between its corners rather than
// a halo: split it into panels for a source that moves across it.
//
// **Once a light is set, it holds for the whole scene.** A surface out of
// range goes dark rather than keeping its colour — otherwise the boundary
// between a surface a light reaches and one it does not would be a hard step
// in the middle of continuous geometry.
typedef struct ScgLight {
  // X coordinate of its position, in world space.
  float x;
  // Y coordinate.
  float y;
  // Z coordinate.
  float z;
  // Its radius, beyond which it lights nothing.
  //
  // Finite and strictly positive. Falloff reaches zero at the radius **with
  // a zero derivative**, so no ring marks the edge — which a falloff linear
  // in squared distance would draw.
  float radius;
  // Red, in the memory order of the output pixels.
  uint8_t r;
  // Green.
  uint8_t g;
  // Blue.
  uint8_t b;
  // Reserved, must be zero.
  //
  // **Not an alpha**: a light adds, it does not blend, so a fourth channel
  // would be a value the engine ignores. The byte exists to keep the
  // structure free of implicit padding, and a later version may give it a
  // meaning — which is why zero is required rather than merely advised.
  uint8_t _reserved;
} ScgLight;

// A 4x4 model matrix, column-major: `m[column * 4 + row]`.
//
// The last row — `m[3]`, `m[7]`, `m[11]`, `m[15]` — must be exactly
// `0, 0, 0, 1`. The engine composes the view itself and inverts the camera
// pose without a division, which only holds for a rigid transform: a
// projection or a perspective matrix passed here would be treated as one.
typedef struct ScgMat4 {
  // The sixteen coefficients, column by column.
  float m[16];
} ScgMat4;

// A vertex position in object space.
typedef struct ScgVertex {
  // X coordinate.
  float x;
  // Y coordinate.
  float y;
  // Z coordinate.
  float z;
} ScgVertex;

// A triangle: three indices into the vertex array, and its colour.
//
// Indices are not optional: a host without indexed geometry writes 0, 1, 2
// then 3, 4, 5. The colour belongs to the triangle rather than to the batch,
// so a whole surface crosses the boundary in one call.
//
// Vertices are counter-clockwise as seen from the front face; a triangle given
// the other way round is a back face and is discarded.
typedef struct ScgTriangle {
  // Index of the first vertex.
  uint32_t i0;
  // Index of the second vertex.
  uint32_t i1;
  // Index of the third vertex.
  uint32_t i2;
  // Red, in the memory order of the output pixels.
  uint8_t r;
  // Green.
  uint8_t g;
  // Blue.
  uint8_t b;
  // Alpha. Ignored: the output is always fully opaque, as the ABI
  // guarantees. The field only exists because a colour has four channels.
  uint8_t a;
} ScgTriangle;

// What a texture load is given.
//
// All fields are `uint32_t`: four-byte alignment on every target, no padding,
// offsets 0 to 20 alike everywhere.
//
// **Both sides must be powers of two**, independently of each other, from 1
// to 2048. Texture coordinates then wrap by masking, with no division and no
// comparison per texel, which is what makes textured filling affordable in
// software.
//
// Zero the whole structure before filling it: the reserved fields must be
// zero, and that is what will allow one of them to be used later without
// breaking bindings already written.
typedef struct ScgTextureDesc {
  // Width in texels, a power of two between 1 and 2048.
  uint32_t width;
  // Height in texels, a power of two between 1 and 2048.
  uint32_t height;
  // Pixel format: `SCG_TEXTURE_FORMAT_RGBA8`.
  uint32_t format;
  // Reserved, must be zero.
  uint32_t reserved0;
  // Reserved, must be zero.
  uint32_t reserved1;
  // Reserved, must be zero.
  uint32_t reserved2;
} ScgTextureDesc;

// A vertex carrying its texture coordinates.
//
// Twenty bytes, offsets 0/4/8/12/16 on every target, with no padding: a
// JavaScript binding writes them into linear memory byte by byte.
//
// `u` and `v` are **in texels, not normalised**. That is the only choice that
// makes them checkable against the vertex array alone: normalised, their bound
// would depend on whichever texture the batch is finally drawn with.
typedef struct ScgVertexUv {
  // X coordinate, in object space.
  float x;
  // Y coordinate.
  float y;
  // Z coordinate.
  float z;
  // Texture abscissa, in texels.
  float u;
  // Texture ordinate, in texels.
  float v;
} ScgVertexUv;

// A vertex carrying a second set of coordinates, the one a lightmap is read
// with.
//
// Twenty-eight bytes, offsets 0 to 24 on every target, with no padding.
//
// **A separate type rather than two more fields on `ScgVertexUv`**, which is
// published and never widens: a host that lights nothing keeps writing five
// floats per vertex.
//
// The two sets are independent, and that is the whole point: a wall repeats
// its texture several times over and stretches its lightmap once across its
// whole extent. Both are in texels of their own image, and both are bounded
// the same way.
typedef struct ScgVertexUv2 {
  // X coordinate, in object space.
  float x;
  // Y coordinate.
  float y;
  // Z coordinate.
  float z;
  // Texture abscissa, in texels.
  float u;
  // Texture ordinate, in texels.
  float v;
  // Lightmap abscissa, in texels of the lightmap.
  float u2;
  // Lightmap ordinate, in texels of the lightmap.
  float v2;
} ScgVertexUv2;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Returns the ABI version of the loaded library.
//
// Callable from any thread, at any time. Bindings that receive it as a signed
// integer — JNI `jint`, JavaScript on wasm — must compare the unsigned value.
uint32_t scg_abi_version(void);

// Creates a rendering context and writes it to `out`.
//
// Zero `*config` entirely before filling it in: its reserved fields must be
// zero. On failure nothing is written to `out`, and the reason is available
// from `scg_last_error(NULL)` on this same thread, read immediately.
//
// # Safety
//
// `config` points to a readable `ScgContextConfig`, and `out` to a writable
// pointer. Both must be non-null.
int32_t scg_create(const struct ScgContextConfig *config, struct ScgContext **out);

// Releases a context.
//
// Passing NULL does nothing, like `free`. A handle destroyed twice, or used
// after destruction, is not detected: that is a precondition, not an error
// case. Destroying a faulted context is allowed.
//
// # Safety
//
// `ctx` is NULL, or a handle returned by `scg_create` and not yet destroyed.
void scg_destroy(struct ScgContext *ctx);

// Sets the camera the next frames will render from.
//
// Rejected with `SCG_ERR_INVALID_STATE` between `scg_frame_begin` and
// `scg_frame_end`, and **as soon as a triangle of the current frame is kept**:
// the camera holds for a whole frame, and every submission projects
// immediately, so a camera changed midway would leave two screen spaces in the
// same image, each one correct and the whole wrong. Set it before submitting,
// or after `scg_frame_end`.
//
// The field of view must be within ]0, pi[ radians and the near plane
// positive, otherwise `SCG_ERR_INVALID_ARGUMENT`. The quaternion is normalised
// by the engine.
//
// # Safety
//
// `ctx` is a live handle used by no other thread during the call, and `camera`
// is NULL or points to a readable `ScgCamera`.
int32_t scg_set_camera(struct ScgContext *ctx, const struct ScgCamera *camera);

// Sets the internal resolution, from the next frames on.
//
// Both sides must be at least 1 and within the `max_width` and `max_height`
// given to `scg_create`, otherwise `SCG_ERR_INVALID_ARGUMENT` and the context
// keeps the resolution it had. Nothing is allocated: every buffer a frame
// needs was sized for the maximum, which is why that maximum is fixed once
// and cannot be raised.
//
// Rejected with `SCG_ERR_INVALID_STATE` between `scg_frame_begin` and
// `scg_frame_end`, and as soon as a triangle of the current frame is kept —
// the same rule as `scg_set_camera`, and for the same reason: projection
// happens at submission time.
//
// **The output buffer does not follow on its own.** After a raise, a buffer
// left at its former size is too short, and the engine cannot detect it — it
// never receives the length. Resize it, and pass the new `stride`. The tile
// count changes too: call `scg_frame_begin` again rather than reusing the
// count from the previous frame.
//
// # Safety
//
// `ctx` is a live handle used by no other thread during the call.
int32_t scg_set_resolution(struct ScgContext *ctx, uint32_t width, uint32_t height);

// Sets the output curve applied while each tile is copied out.
//
// See `ScgGrade` for what the fields mean and what the reserved ones may ever
// hold. Out-of-range values, or a reserved field that is not zero, return
// `SCG_ERR_INVALID_ARGUMENT` and the context keeps the curve it had.
//
// Neutral by default, and turned back to neutral by `scg_clear_grade`. It
// costs three table lookups per pixel once set, and nothing at all while it is
// neutral. Rejected with `SCG_ERR_INVALID_STATE` between `scg_frame_begin` and
// `scg_frame_end`, for the reason that holds for every frame-wide setting.
//
// # Safety
//
// `ctx` is a live handle used by no other thread during the call, and `grade`
// is NULL or points to a readable `ScgGrade`.
int32_t scg_set_grade(struct ScgContext *ctx, const struct ScgGrade *grade);

// Returns the output to its neutral state.
//
// Doing so on a context that never set a curve is not an error: a host that
// flattens its output at the end of a level does not have to remember whether
// it had set one.
//
// # Safety
//
// `ctx` is a live handle used by no other thread during the call.
int32_t scg_clear_grade(struct ScgContext *ctx);

// Sets how textures are sampled from the next frames on.
//
// `filter` is `SCG_FILTER_DITHER`, the default, or `SCG_FILTER_BILINEAR`; any
// other value is `SCG_ERR_INVALID_ARGUMENT`, and the context keeps the filter
// it had. A binding written against a later version therefore gets a plain
// error rather than an image filtered otherwise than it believes.
//
// Rejected with `SCG_ERR_INVALID_STATE` between `scg_frame_begin` and
// `scg_frame_end`: tiles of one frame are rendered from threads the engine
// knows nothing about, and a filter changed in between would leave part of the
// image sampled one way and part the other.
//
// The two filters are exclusive: bilinear replaces dithering, it does not add
// to it.
//
// # Safety
//
// `ctx` is a live handle used by no other thread during the call.
int32_t scg_set_filter(struct ScgContext *ctx, uint32_t filter);

// Sets how much lit surfaces are brightened, from the next frames on.
//
// `shift` is `0`, `1` or `2`; anything else is `SCG_ERR_INVALID_ARGUMENT`,
// and the context keeps the value it had.
//
// **Zero is the default, and it is the faithful setting**: under full light a
// texel comes out untouched, and never brighter. It is also a dull scene —
// a real lightmap reaches white nowhere, so every surface ends up darker than
// its texture. One or two double or quadruple the combined value, saturating
// where light is strong, and that is what gives a lit scene its range.
//
// Rejected with `SCG_ERR_INVALID_STATE` between `scg_frame_begin` and
// `scg_frame_end`, for the same reason as `scg_set_filter`: a frame whose
// tiles did not all share one setting is described by nothing.
//
// # Safety
//
// `ctx` is a live handle used by no other thread during the call.
int32_t scg_set_overbright(struct ScgContext *ctx, uint32_t shift);

// Turns on distance fog, from the next frames on.
//
// `start` and `end` are view distances in world units, counted from the
// camera: `start` must be finite and not negative, `end` finite and strictly
// beyond `start`. Anything else is `SCG_ERR_INVALID_ARGUMENT`, and the
// context keeps the fog it had.
//
// **The image's background takes the fog colour on its own**, without the
// host clearing with it: a pixel no triangle painted is infinitely distant,
// and fog is applied where depth is already at hand. That is what makes
// distant geometry meet the horizon with no dividing line — clearing
// separately would draw back the very seam this avoids.
//
// **Three channels, not four.** The output buffer is opaque by contract, so
// an alpha on the fog colour would be a value the engine ignores, and a host
// would rightly wonder what it does.
//
// Off by default, and turned off again by `scg_clear_fog`. Rejected with
// `SCG_ERR_INVALID_STATE` between `scg_frame_begin` and `scg_frame_end`, for
// the reason that holds for every frame setting.
//
// # Safety
//
// `ctx` is a live handle used by no other thread during the call.
int32_t scg_set_fog(struct ScgContext *ctx,
                    uint8_t r,
                    uint8_t g,
                    uint8_t b,
                    float start,
                    float end);

// Turns distance fog off, from the next frames on.
//
// Calling it on a context that has no fog is not an error: a host that turns
// fog off at the end of a level does not have to remember whether it turned
// it on.
//
// Rejected with `SCG_ERR_INVALID_STATE` during a frame, like every other
// frame setting.
//
// # Safety
//
// `ctx` is a live handle used by no other thread during the call.
int32_t scg_clear_fog(struct ScgContext *ctx);

// Replaces the dynamic lights of the frames to come.
//
// At most eight; beyond that the whole call is rejected rather than
// truncated, since a half-lit scene looks exactly like one whose radii are
// wrong. A count of zero turns lighting off.
//
// **Falloff is computed per vertex, when a batch is submitted**: lights set
// after a batch do not reach it. That is what lets a torch carried by the
// player light a set without the set being submitted again — provided it is
// set first.
//
// **Once a light is set, it holds for the whole scene.** A surface out of
// range goes dark rather than keeping its colour: the boundary between a
// surface a light reaches and one it does not would otherwise be a hard step
// in the middle of continuous geometry.
//
// A light whose position is not finite, or whose radius is not finite and
// strictly positive, is rejected: it would light nothing and divide by zero.
//
// Rejected with `SCG_ERR_INVALID_STATE` during a frame, like every other
// frame setting.
//
// # Safety
//
// `ctx` is a live handle used by no other thread during the call, and
// `lights` points to `count` readable `ScgLight`. A count of zero allows a
// null pointer.
int32_t scg_set_lights(struct ScgContext *ctx, const struct ScgLight *lights, uint32_t count);

// Submits a batch of triangles to the frame being recorded.
//
// `model` carries the object into world space; the engine composes the view
// from its own camera. Passing a model-view matrix here would apply the view
// twice.
//
// Each triangle indexes three vertices of `vertices` and carries its own
// colour. **The batch is accepted or rejected as a whole**: an index at or
// beyond `vertex_count`, a coefficient that is not finite, or a batch that
// would exceed the triangle capacity leaves the frame exactly as it was. A
// triangle whose vertices cannot be projected — beyond the guard band, behind
// the near plane — simply does not appear, which is not an error.
//
// A count of zero is accepted and submits nothing. Rejected with
// `SCG_ERR_INVALID_STATE` between `scg_frame_begin` and `scg_frame_end`.
//
// # Safety
//
// `ctx` is a live handle used by no other thread during the call; `vertices`
// points to `vertex_count` readable `ScgVertex`, and `triangles` to
// `triangle_count` readable `ScgTriangle`. A count of zero allows a null
// pointer.
int32_t scg_submit(struct ScgContext *ctx,
                   const struct ScgMat4 *model,
                   const struct ScgVertex *vertices,
                   uint32_t vertex_count,
                   const struct ScgTriangle *triangles,
                   uint32_t triangle_count);

// Begins a frame: seals the submitted scene, bins it into tiles, and writes
// the tile count to `tile_count`.
//
// Tiles are numbered row by row, left to right then top to bottom; those of
// the last column and row are partial when the internal resolution is not a
// multiple of the tile size. A frame already begun returns
// `SCG_ERR_INVALID_STATE`.
//
// Rendering the tiles is optional: `scg_frame_end` renders every tile nobody
// rendered.
//
// # Safety
//
// `ctx` is a live handle used by no other thread during the call, and
// `tile_count` is NULL or writable.
int32_t scg_frame_begin(struct ScgContext *ctx, uint32_t *tile_count);

// Renders tile `index` of the frame begun by `scg_frame_begin` into the host
// buffer.
//
// Callable from several threads at once on the same context, for distinct
// indices, and only between `scg_frame_begin` and `scg_frame_end`; no other
// call on the context is allowed meanwhile. A tile renders once per frame: an
// index already taken, even by a concurrent call, returns
// `SCG_ERR_INVALID_STATE`, as does a tile outside a begun frame. An index at or
// beyond the tile count returns `SCG_ERR_INVALID_ARGUMENT`.
//
// The error message of this call goes to the per-thread slot: read it with
// `scg_last_error(NULL)` on the calling thread, immediately after the call.
// A panic faults the context; the other tiles already running complete, and
// `scg_frame_end` reports it.
//
// Each tile keeps its colour and depth on the stack of the call: the calling
// thread needs at least 128 KiB of stack.
//
// `pixels` and `stride` are those of the whole image, the same for every tile
// and for `scg_frame_end` of the frame: the tile writes only its own rectangle.
//
// # Safety
//
// `ctx` is a live handle, and `pixels` points to a writable buffer of at least
// `stride × height × 4` bytes.
int32_t scg_frame_tile(struct ScgContext *ctx, uint32_t index, uint8_t *pixels, uint32_t stride);

// Ends the frame and writes the result into the host buffer.
//
// It renders every tile nobody rendered, then closes the frame. Without
// `scg_frame_begin`, it begins the frame itself: a host that only ever calls
// this function always receives the whole image. While a tile is still being
// rendered on another thread, it returns `SCG_ERR_INVALID_STATE` and leaves
// the frame open. Its return code is what tells whether the image is good.
//
// `stride` is in pixels and must be at least the current internal width. The
// buffer holds at least `stride × height` pixels of four bytes each, in R, G,
// B, A order with alpha always written. The engine never receives the buffer
// length and cannot check it: that is a documented precondition.
//
// # Safety
//
// `ctx` is a live handle, and `pixels` points to a writable buffer of at least
// `stride × height × 4` bytes.
int32_t scg_frame_end(struct ScgContext *ctx, uint8_t *pixels, uint32_t stride);

// Returns the last error message, as a NUL-terminated UTF-8 string.
//
// The pointer is valid until the next call on the same context: copy the
// message immediately if you need to keep it. It is never NULL — with no error
// since the last call, the message is the empty string. The string belongs to
// the engine; never free it.
//
// Pass NULL to read the message of calls that have no context to attach it to,
// such as a failed `scg_create`. That slot is per thread, not per call: read it
// on the thread that made the failing call, immediately after it. A coroutine
// that resumes on another thread of a pool will find it empty.
//
// Allowed on a faulted context, so the host can learn the cause.
//
// # Safety
//
// `ctx` is NULL, or a handle returned by `scg_create` and not yet destroyed.
const char *scg_last_error(const struct ScgContext *ctx);

// Allocates a buffer the host owns until `scg_buffer_free`.
//
// Returns NULL on failure, and for a length of zero. The block is aligned to
// `SCG_BUFFER_ALIGNMENT` bytes.
//
// On wasm this is the only way to obtain a buffer the engine can write to: the
// host cannot hand over an arbitrary pointer, since only the module's linear
// memory is addressable. In JavaScript the returned pointer arrives signed —
// test it with `ptr === 0`, never `ptr > 0`, and convert with `ptr >>> 0`
// before building a view.
//
// Callable from any thread.
uint8_t *scg_buffer_alloc(size_t len);

// Releases a buffer obtained from `scg_buffer_alloc`.
//
// `len` must be exactly the length passed to the allocation: the allocator
// rebuilds the block description from it, and a different value is undefined
// behaviour. Passing NULL does nothing. These blocks are freed through this
// function and no other — the engine's allocator is not the host's, on desktop
// either.
//
// Callable from any thread.
//
// # Safety
//
// `ptr` is NULL, or a pointer returned by `scg_buffer_alloc` and not yet
// freed, with the same `len`.
void scg_buffer_free(uint8_t *ptr, size_t len);

// Loads a texture from a block of pixels and writes its handle to `out`.
//
// `pixels` holds `width * height` texels, rows contiguous, four bytes each in
// R, G, B, A order — the memory order of the output pixels. The block is
// copied: the host may free it as soon as this call returns.
//
// **Both sides must be powers of two**, independently, from 1 to 2048. The
// whole mipmap chain is built here, down to 1x1, by averaging texels; nothing
// is ever generated later, which is what keeps a frame free of allocation.
//
// **Takes no context.** A texture belongs to none, and the same one may be
// submitted to several from several threads. On failure the message therefore
// goes to the per-thread slot: read it with `scg_last_error(NULL)`, on the
// calling thread, before any other call on that thread.
//
// # Safety
//
// `desc` must point to a readable description, zeroed before being filled in.
// `pixels` must cover exactly `width * height * 4` readable bytes, and `out` a
// writable handle. Nothing is written to `out` on failure.
int32_t scg_texture_load(const struct ScgTextureDesc *desc,
                         const uint8_t *pixels,
                         size_t len,
                         struct ScgTexture **out);

// Releases a texture.
//
// `scg_texture_destroy(NULL)` does nothing, like `free(NULL)`. Destroying a
// texture a frame still references is harmless: the engine holds its own
// reference until that frame ends.
//
// # Safety
//
// `texture` must be null, or a handle returned by `scg_texture_load` and not
// yet destroyed.
void scg_texture_destroy(struct ScgTexture *texture);

// Submits a batch of triangles dressed with a texture.
//
// Same contract as `scg_submit`, with two differences: the vertices carry
// their texture coordinates, in texels, and the texture applies to the whole
// batch. Coordinates beyond 16384 texels, or not finite, reject the batch.
//
// Each triangle's colour is **ignored** on this path: the texel decides, and
// the colour does not tint it. Fill `r`, `g`, `b` and `a` with anything.
//
// # Safety
//
// Same preconditions as `scg_submit`, and `texture` must be a live handle from
// `scg_texture_load`.
int32_t scg_submit_textured(struct ScgContext *ctx,
                            const struct ScgMat4 *model,
                            const struct ScgVertexUv *vertices,
                            uint32_t vertex_count,
                            const struct ScgTriangle *triangles,
                            uint32_t triangle_count,
                            const struct ScgTexture *texture);

// Submits a batch of triangles lit by a lightmap.
//
// Same contract as `scg_submit_textured`, with two differences: the vertices
// carry a second set of coordinates, and the batch carries a lightmap on top
// of its texture. Both apply to the whole batch.
//
// **`texture` may be null, and `lightmap` may not.** That asymmetry is
// deliberate and is the one thing to get right here: a plain wall lit by a
// lightmap is the commonest surface of a set, and it renders `colour x
// lightmap`, each triangle's own colour standing in for the texel. A null
// `lightmap`, on the other hand, is `SCG_ERR_NULL` — a batch without one has
// no business on this path, and `scg_submit` or `scg_submit_textured` renders
// it.
//
// Where `texture` is given, each triangle's colour is ignored exactly as on
// `scg_submit_textured`.
//
// The lightmap is read bilinearly whatever `scg_set_filter` says, and through
// its own mipmap chain. The engine keeps its own strong reference to both
// images until the end of the frame: a host may destroy them on return.
//
// # Safety
//
// Same preconditions as `scg_submit`, `vertices` pointing to `vertex_count`
// readable `ScgVertexUv2`; `lightmap` must be a live handle from
// `scg_texture_load`, and `texture` must be null or such a handle.
int32_t scg_submit_lit(struct ScgContext *ctx,
                       const struct ScgMat4 *model,
                       const struct ScgVertexUv2 *vertices,
                       uint32_t vertex_count,
                       const struct ScgTriangle *triangles,
                       uint32_t triangle_count,
                       const struct ScgTexture *texture,
                       const struct ScgTexture *lightmap);

// Loads a mesh from a block of bytes.
//
// The engine copies what it keeps: the host may free `bytes` as soon as the
// call returns, and no lifetime crosses the boundary. `len` must be exactly the
// length the file declares in its header — a longer or shorter block is
// rejected, tail bytes included.
//
// The mesh belongs to no context, so the failure is read with
// `scg_last_error(NULL)`. Two codes say different things to the host:
// `SCG_ERR_INVALID_FORMAT` means the content is bad, to report as a bad asset;
// `SCG_ERR_UNSUPPORTED_FORMAT_VERSION` means this library cannot read that
// version, so take a newer one or export the data again.
//
// An empty mesh is a valid file, not an error.
//
// # Safety
//
// `bytes` must cover `len` readable bytes, or `len` must be zero. `out` must
// point to a writable handle; nothing is written unless the call succeeds.
int32_t scg_mesh_load(const uint8_t *bytes, size_t len, struct ScgMesh **out);

// Releases a mesh.
//
// `scg_mesh_destroy(NULL)` does nothing, like `free(NULL)`. Destroying a mesh
// during a frame is harmless, but **not for the same reason as a texture**:
// nothing reads a mesh once the submission has returned, whereas the engine
// holds a reference to a texture until the frame ends. Do not assume the two
// follow one rule.
//
// # Safety
//
// `mesh` must be null, or a handle returned by `scg_mesh_load` and not yet
// destroyed.
void scg_mesh_destroy(struct ScgMesh *mesh);

// Writes the number of texture slots the mesh asks for to `out`.
//
// Slots are numbered from zero. Read each name with `scg_mesh_texture_name`,
// load what you want with your own files, and pass the handles in slot order.
//
// # Safety
//
// `mesh` must be a live handle from `scg_mesh_load`, and `out` must point to a
// writable `uint32_t`.
int32_t scg_mesh_texture_count(const struct ScgMesh *mesh, uint32_t *out);

// Reads the name of one texture slot, in two steps.
//
// Call it once with `buf` null and `cap` zero: it writes the length of the name
// to `out_len`, not counting the terminator. Call it again with a buffer of at
// least `*out_len + 1` bytes: it writes the name and a null terminator.
//
// A `cap` too small for the name and its terminator returns
// `SCG_ERR_INVALID_ARGUMENT` and **writes nothing**, `out_len` included — the
// measuring call is how you learn the length. A `slot` beyond
// `scg_mesh_texture_count` returns `SCG_ERR_INVALID_ARGUMENT` too: the file is
// fine, the index is not. `out_len` is required in both steps.
//
// The name is what the file calls the slot, never a path: the engine opens
// nothing, and the host decides what it loads for that slot.
//
// # Safety
//
// `mesh` must be a live handle from `scg_mesh_load`. `buf` must be null with
// `cap` zero, or cover `cap` writable bytes. `out_len` must point to a writable
// `size_t`.
int32_t scg_mesh_texture_name(const struct ScgMesh *mesh,
                              uint32_t slot,
                              char *buf,
                              size_t cap,
                              size_t *out_len);

// Writes the number of triangles the mesh carries to `out`.
//
// It is what a host needs to size `max_triangles` before creating the context
// it will submit to: without it, the only way to know is to try.
//
// # Safety
//
// `mesh` must be a live handle from `scg_mesh_load`, and `out` must point to a
// writable `uint32_t`.
int32_t scg_mesh_triangle_count(const struct ScgMesh *mesh, uint32_t *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SCREENGINE_H */

/* cbindgen puts this block after the include guard, so it needs one of its own. */
#ifndef SCREENGINE_LAYOUT_CHECKED
#define SCREENGINE_LAYOUT_CHECKED
#if defined(__cplusplus) && (__cplusplus >= 201103L || (defined(_MSVC_LANG) && _MSVC_LANG >= 201103L))
#define SCREENGINE_LAYOUT_ASSERT(cond, what) static_assert(cond, what)
#elif !defined(__cplusplus) && defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#define SCREENGINE_LAYOUT_ASSERT(cond, what) _Static_assert(cond, what)
#endif
#ifdef SCREENGINE_LAYOUT_ASSERT
SCREENGINE_LAYOUT_ASSERT(sizeof(ScgContextConfig) == 32, "ScgContextConfig changed size");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgContextConfig, max_width) == 0, "max_width moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgContextConfig, max_height) == 4, "max_height moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgContextConfig, width) == 8, "width moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgContextConfig, height) == 12, "height moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgContextConfig, tile_size) == 16, "tile_size moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgContextConfig, max_triangles) == 20, "max_triangles moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgContextConfig, reserved1) == 24, "reserved1 moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgContextConfig, reserved2) == 28, "reserved2 moved");
SCREENGINE_LAYOUT_ASSERT(sizeof(ScgVertex) == 12, "ScgVertex changed size");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgVertex, z) == 8, "ScgVertex.z moved");
SCREENGINE_LAYOUT_ASSERT(sizeof(ScgTriangle) == 16, "ScgTriangle changed size");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgTriangle, i2) == 8, "ScgTriangle.i2 moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgTriangle, r) == 12, "ScgTriangle.r moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgTriangle, a) == 15, "ScgTriangle.a moved");
SCREENGINE_LAYOUT_ASSERT(sizeof(ScgVertexUv) == 20, "ScgVertexUv changed size");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgVertexUv, z) == 8, "ScgVertexUv.z moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgVertexUv, u) == 12, "ScgVertexUv.u moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgVertexUv, v) == 16, "ScgVertexUv.v moved");
SCREENGINE_LAYOUT_ASSERT(sizeof(ScgVertexUv2) == 28, "ScgVertexUv2 changed size");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgVertexUv2, z) == 8, "ScgVertexUv2.z moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgVertexUv2, u) == 12, "ScgVertexUv2.u moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgVertexUv2, v) == 16, "ScgVertexUv2.v moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgVertexUv2, u2) == 20, "ScgVertexUv2.u2 moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgVertexUv2, v2) == 24, "ScgVertexUv2.v2 moved");
SCREENGINE_LAYOUT_ASSERT(sizeof(ScgLight) == 20, "ScgLight changed size");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgLight, z) == 8, "ScgLight.z moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgLight, radius) == 12, "ScgLight.radius moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgLight, r) == 16, "ScgLight.r moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgLight, _reserved) == 19, "ScgLight._reserved moved");
SCREENGINE_LAYOUT_ASSERT(sizeof(ScgTextureDesc) == 24, "ScgTextureDesc changed size");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgTextureDesc, height) == 4, "ScgTextureDesc.height moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgTextureDesc, format) == 8, "ScgTextureDesc.format moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgTextureDesc, reserved2) == 20, "ScgTextureDesc.reserved2 moved");
SCREENGINE_LAYOUT_ASSERT(sizeof(ScgGrade) == 36, "ScgGrade changed size");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgGrade, gain_r) == 4, "ScgGrade.gain_r moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgGrade, gain_b) == 12, "ScgGrade.gain_b moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgGrade, offset_r) == 16, "ScgGrade.offset_r moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgGrade, offset_b) == 24, "ScgGrade.offset_b moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgGrade, reserved0) == 28, "ScgGrade.reserved0 moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgGrade, reserved1) == 32, "ScgGrade.reserved1 moved");
SCREENGINE_LAYOUT_ASSERT(sizeof(ScgCamera) == 36, "ScgCamera changed size");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgCamera, orientation) == 12, "orientation moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgCamera, fov_y) == 28, "fov_y moved");
SCREENGINE_LAYOUT_ASSERT(offsetof(ScgCamera, near_plane) == 32, "near_plane moved");
SCREENGINE_LAYOUT_ASSERT(sizeof(ScgMat4) == 64, "ScgMat4 changed size");
#undef SCREENGINE_LAYOUT_ASSERT
#endif
#endif
