/*
 * Copyright 2026 Stéphane Primault <sprimault@users.noreply.github.com>
 * SPDX-License-Identifier: MIT
 */

#ifndef SCREENGINE_H
#define SCREENGINE_H

/* Generated by cbindgen from screengine-ffi. Do not edit by hand: run `make header`. */

#include <stddef.h>
#include <stdint.h>

#endif  /* SCREENGINE_H */
